In [1]:
import cv2
# from inference import infer_image, load_models

# # Load models
# deepc_path = './reference/longrun-epoch=99-step=369700.ckpt'
# refinenet_path = './reference/second-refinenet-epoch-100-step=373k.ckpt'
# n_ids = 9
#  # The number of corners (models pretrained use 16 for default board)
# device = 'cuda'   # use device: cpu / mps / cuda
# refinenet = load_models(refinenet_path, device='cuda')

# Run inference on BGR image
dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
parameters = cv2.aruco.DetectorParameters_create()
#detector = cv2.aruco.ArucoDetector(dictionary, parameters)
img = cv2.imread('/home/alessia/Desktop/test_prep/render_00001.png',cv2.IMREAD_GRAYSCALE)
detected_corners, ids, rejected = cv2.aruco.detectMarkers(img, dictionary, parameters=parameters)



In [2]:
import numpy as np
true=np.array([[
                1351.4615151519317,
                491.37359077983984
            ],
            [
                1249.593499297048,
                474.523892470125
            ],
            [
                1226.601292924053,
                568.4999200648358
            ],
            [
                1329.536311643521,
                585.3341630044895
            ]])
print(detected_corners)

(array([[[1332.,  591.],
        [1226.,  574.],
        [1250.,  477.],
        [1355.,  495.]]], dtype=float32),)


In [5]:
for j in range(4):
    center_coordinates = (int(np.round(true[j][0])),int(np.round(true[j][1])))
    img = cv2.circle(img, center_coordinates, 1, (0,255,0), 1) 
    center_coordinates = (int(np.round(detected_corners[0][0][j][0])),int(np.round(detected_corners[0][0][j][1])))
    img = cv2.circle(img, center_coordinates, 3, (0,0,255), 1) 
img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
cv2.namedWindow('True corners ', cv2.WND_PROP_FULLSCREEN)
cv2.setWindowProperty('True corners ', cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
cv2.imshow('True corners ', img )
cv2.waitKey(0) #uncomment to see the image
cv2.destroyAllWindows()

AttributeError: module 'cv2' has no attribute 'COLOR_GRAY2RBG'

In [3]:
def click_event(event, x, y, flags, param):
    # Check for left mouse button click
    if event == cv2.EVENT_LBUTTONDOWN:
        # Print the coordinates to the console
        print(f"Clicked coordinates: ({x}, {y})")

        # Optionally, display the coordinates on the image
        font = cv2.FONT_HERSHEY_SIMPLEX



cv2.namedWindow("image", cv2.WND_PROP_FULLSCREEN)
cv2.setWindowProperty("image", cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
# # Display the image in a window
# cv2.imshow('image', img)

# # Set the mouse callback function to 'click_event'
# cv2.setMouseCallback('image', click_event)

# # Wait until a key is pressed
# cv2.waitKey(0)

# Destroy all OpenCV windows
cv2.destroyAllWindows()


In [4]:
cv2.namedWindow('img', cv2.WND_PROP_FULLSCREEN)
cv2.setWindowProperty('img', cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
# cv2.imshow('img',img)
# cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
import numpy as np
keypoint=np.array([[3368., 615.]]).astype(np.int64)
print(keypoint)

[[3368  615]]


In [6]:
keypoints, out_img = infer_image(img, keypoint, 1, refinenet, draw_pred=True, device='cuda')

print(keypoints)


torch.int64
torch.int64
torch.int64
torch.float32
float32
[[3.3715000e+03 6.1187500e+02 9.2141264e+33]]


In [7]:
cv2.namedWindow('out img', cv2.WND_PROP_FULLSCREEN)
cv2.setWindowProperty('out img', cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
cv2.imshow('out img',out_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
cropped_image=out_img[612-12:612+12, 3368-12:3368+12]
print(cropped_image.shape)
cv2.namedWindow('out img', cv2.WND_PROP_FULLSCREEN)
cv2.setWindowProperty('out img', cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
cv2.imshow('out img',cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

(24, 24, 3)


In [9]:

# # The out_img will have corners plotted on it if draw_pred is True
# # The keypoints format is (x, y, id_corner)
# keypoints, out_img = infer_image(img, n_ids, deepc, refinenet, draw_pred=True, device=device)
from inference import solve_pnp

# load your intrinsics as camera_matrix and dist_coeffs
# check calib_intrinsics for a reference how I generated them.
# Check the solve pnp function and adapt it to your needs.
# ret, rvec, tvec = solve_pnp(keypoints, col_count, row_count, square_len,
#                             camera_matrix, dist_coeffs)